# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10


jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: "Build"
          command: ./gradlew clean build

      - persist_to_workspace:
          root: build/libs
          paths:
            - stufffriendssay-*-all.jar

      - store_test_results:
          path: build/test-results

  deploy:
    steps:
      - attach_workspace:
          at: build/libs

      - heroku/install

      - run:
          name: "Install java plugin"
          command: |
            heroku plugins:install java

      - run:
          name: "Deploy jar"
          command: |
            heroku deploy:jar build/libs/stufffriendssay-*-all.jar --app $HEROKU_APP_NAME

workflows:
  version: 2
  stuffFriendsSay:
    jobs:
      - build
      - deploy:
          requires:
            - build
